USE ROLE TRANSFORM;
USE WAREHOUSE OLIST_WH;
USE DATABASE OLIST_DB;
USE SCHEMA RAW;

SELECT 'Customers' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM OLIST_DB.RAW.raw_customers
UNION 
SELECT 'Orders' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM OLIST_DB.RAW.raw_orders
UNION  
SELECT 'Order Items' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM OLIST_DB.RAW.raw_order_items
UNION 
SELECT 'Order Payments' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM OLIST_DB.RAW.raw_order_payments
UNION 
SELECT 'Order Reviews' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM OLIST_DB.RAW.raw_order_reviews
UNION 
SELECT 'Products' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM OLIST_DB.RAW.raw_products
UNION 
SELECT 'Sellers' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM OLIST_DB.RAW.raw_sellers
UNION
SELECT 'Geolocation' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM OLIST_DB.RAW.raw_geolocation
UNION
SELECT 'Product Category Translation' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM OLIST_DB.RAW.raw_product_category_translation;
