# This file allows you to configure Airflow Connections, Pools, and Variables in a single place for local development only.
# NOTE: json dicts can be added to the conn_extra field as yaml key value pairs. See the example below.

# For more information, refer to our docs: https://www.astronomer.io/docs/astro/cli/develop-project#configure-airflow_settingsyaml-local-development-only
# For questions, reach out to: https://support.astronomer.io
# For issues create an issue ticket here: https://github.com/astronomer/astro-cli/issues

airflow:
  connections:
    - conn_id: snowflake_olist
      conn_type: snowflake
      conn_host:
      conn_schema: RAW
      conn_login: DBT
      conn_password: OlistDBT_Snowflakeuser1993
      conn_port:
      conn_extra: |
        {
          "account": "AFISPTQ-YQ17301",
          "warehouse": "OLIST_WH",
          "database": "OLIST_DB",
          "role": "TRANSFORM"
        }

  pools:
    - pool_name:
      pool_slot:
      pool_description:

  variables:
    - variable_name:
      variable_value:
